# Generated by Django 6.1.1 on 2026-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('food_type', models.CharField(choices=[('prepared', 'Prepared Meals'), ('baked', 'Baked Goods'), ('produce', 'Fresh Produce'), ('packaged', 'Packaged Food'), ('beverages', 'Beverages'), ('other', 'Other')], max_length=50)),
                ('donor_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('prepared_at', models.DateTimeField()),
                ('available_until', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
